LIXC-964 Generate license and sent to dev workspace
leanix/microservice-intelligence-action pull request #24
Opened 2020-08-27 10:17 UTC by HenrichN

2020-08-27 11:18 UTC, christophwalpert commented
Hi Niklas, I think you need to check your quotations on lines 32 - 34 and 43 - 45. Please compare for instance line 23 and line 33/44. I think this needs adjustment.

2020-08-27 11:19 UTC, christophwalpert requested changes
Hi Niklas, I think you need to check your quotations on lines 32 - 34 and 43 - 45. Please compare for instance line 23 and line 33/44. I think this needs adjustment.

2020-08-27 11:49 UTC, HenrichN commented
@christophwalpert Good catch, it worked on my machine ;-), but let's do it like you proposed.

2020-08-28 11:23 UTC, christophwalpert approved these changes

2020-09-04 06:51 UTC, merged